### ISSUE TITLE
Why did you pick SVG?

### ISSUE THREAD

**Issue by Restuta** [anvaka/vue-compare#1]
I mean I got it that it's your favorite thing, but based on the sample code you are just testing (in React's case) how much overhead it adds if you re-render everything as fast as you can and so far it's not even close to be optimized for 60fps rendering of animation, they are just starting to think about how to support this. I would do more close-to-real-life tests with dome and stuff. What do you think?

**Comment by anvaka** [comment]
The purposes of the benchmark is to stress the system. Obviously it is a contrived example, but it's less unrealistic than one might expect. 

For example rendering a graph with 1k nodes, and 3k edges - is fairly common task.

**Comment by Restuta** [comment]
@anvaka for you it maybe common, I think people primarily render DOM trees and not with "requestAnimationFrame". I was thinking that community is lacking tests that help bring some light on real-life performance. E.g. typical page has 300-500 components, how fast react renders it? Having results like:

```
Your typical page when you just started 200-1000 components: 100-400ms for first render

Complex page with 1000-2000 components (examples here): 400-800ms for first render
```

etc. so people can make more informed decisions depending on how important first render is (internal pages it's not, public facing it is)

**Comment by anvaka** [comment]
Are you looking for http://httparchive.org/interesting.php ?

There is also good repaint test for popular frameworks here: http://mathieuancelin.github.io/js-repaint-perfs/

**Comment by Restuta** [comment]
Re-painting is different from what I mentioned, I don't write a lot of "re-paint-heavy" apps, as well as most people (I guess), therefore initial paint is more important. (Especially on mobile)

Thanks for the first link, though.
